name: Test action
on:
  workflow_dispatch:
jobs:
  update_contributors:
    runs-on: ubuntu-latest
    steps:
      - name: test-action
        uses: tessus/action-test@a647ea9901eb95de567dffc55099dc6bff161900
        with:
          sort-by-auto-threshold: 20
