name: Test action
on:
  workflow_dispatch:
jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Update Contributors
        uses: tessus/action-test@235a4f9b07ed844b55cbf8c3db07b3e619ede957
        with:
          sort-by-auto-threshold: 20
          exclude: '[bot], Joplin Bot'
