name: Test action
on:
  workflow_dispatch:
jobs:
  update_contributors:
    runs-on: ubuntu-latest
    steps:
      - name: test-action
        uses: tessus/action-test@9831cc08243971ed49371cef5d3dbff029d7c4cb
        with:
          sort-by-auto-threshold: 20
          exclude: '[bot], Joplin Bot'
