name: Update CONTRIBUTORS file
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
  update_contributors:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: retrieve contributors and update file
        run: |
          git log --pretty='%an <%ae>' |sort -uf |grep -v "\[bot\]" >CONTRIBUTORS

      - name: setup git config
        run: |
          git config user.name "github-actions[bot]"

      - name: check for modified files
        id: git-check
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "FILE_MODIFIED=true" >> $GITHUB_OUTPUT
          else
            echo "FILE_MODIFIED=false" >> $GITHUB_OUTPUT
          fi

      - name: commit updated CONTRIBUTORS
        if: steps.git-check.outputs.FILE_MODIFIED == 'true'
        run: |
          git add CONTRIBUTORS
          git commit -m "chore: update CONTRIBUTORS"
          git push
