name: Update CONTRIBUTORS file v3
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
    inputs:
      sort-by:
        description: 'Sort contributors by: name, commits, auto'
        required: false
        default: 'auto'
jobs:
  update_contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Check Runner OS
        if: ${{ runner.os != 'Linux' }}
        shell: bash
        run: |
          echo "This action must be run on Linux."
          exit 1

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Retrieve contributors and update file
        shell: bash
        run: |
          git log |git shortlog -sen |tr '\t' ':' |cut -d: -f2- |sed '/\[bot\]/d' >CONTRIBUTORS

      - name: Retrieve the number of contributors
        id: num-contrib
        shell: bash
        run: |
          NUM=$(cat CONTRIBUTORS |wc -l |xargs)
          echo "NUM_CONTRIB=$NUM" >> $GITHUB_OUTPUT

      - name: Sort by name
        shell: bash
        if: (${{ github.event.inputs.sort-by }}" == 'auto' && steps.num-contrib.outputs.NUM_CONTRIB > 30) || ${{ github.event.inputs.sort-by }}" == 'name'
        run: |
          echo ${{ github.event.inputs.sort-by }} >TEST
          echo ${{ steps.num-contrib.outputs.NUM_CONTRIB }} >>TEST
          cat CONTRIBUTORS |sort -uf >CONTRIBUTORS.sorted
          mv CONTRIBUTORS.sorted CONTRIBUTORS

      - name: Setup git config
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for modified file
        id: git-check
        shell: bash
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "FILE_MODIFIED=true" >> $GITHUB_OUTPUT
          else
            echo "FILE_MODIFIED=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit updated CONTRIBUTORS
        if: steps.git-check.outputs.FILE_MODIFIED == 'true'
        shell: bash
        run: |
          #git add CONTRIBUTORS
          git add -A
          git commit -m "chore: update CONTRIBUTORS"
          git push
