name: Update CONTRIBUTORS file v2
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
  update_contributors:
    runs-on: ubuntu-latest
    steps:
      - name: update
        uses: tessus/update-contributors-list@446e2f93398fff07c519641f9175485b883efafa
